spring:
  #  sql.init:
  #    mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username:
    password:
    driver-class-name: org.postgresql.Driver
#  jpa.properties.hibernate.show_sql: true
#  jpa.hibernate.ddl-auto: none
